### ISSUE TITLE
Dynamic arrow count

### ISSUE THREAD

**Issue by Madis0** [DarkKronicle/KronHUD#10]
**Describe what you would like**
I want to see the arrow count only when holding a bow or crossbow.

**Additional context**
Optionally hiding the arrow icon would be cool too (keeping just the count).

**Comment by DarkKronicle** [comment]
I think it would be kind of weird for it to just disappear whenever you're not using a bow/crossbow. I may add something to stop rendering it when not holding a bow/crossbow.
