### ISSUE TITLE
New module: Chat Window

### ISSUE THREAD

**Issue by heldheld** [DarkKronicle/KronHUD#105]
**Describe what you would like**
A lighter version of the AdvancedChat mods, where you can change the position and size of the Chat easily, similar to the Scoreboard module. Have the same options as the Scoreboard module, together with an option to change the direction of the chat from up to down, and also an option to align it to the right side.

**Additional context**
-

**Comment by DarkKronicle** [comment]
This isn't planned since AdvancedChat is a thing (I know you talked about it, but too much work for just a lighter version to bundle)
