### ISSUE TITLE
Game Crashed After I Pressed "Shift" Key in Order to Set-up This Mod.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [DarkKronicle/KronHUD#113]
**Describe the bug**
My game crashed after I pressed "Shift" key

**To Reproduce**
1. Install this mod on fabric client
2. Try to get into the mod setting.
3. Crashed.

**Expected behavior**
The mod and game run normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/42903464/213914623-926da5c6-06a5-4c73-a9c4-13e16c2399d9.png)

**Additional context**
Here is the crash report. Hope this will help.

[crash-2023-01-22_19.59.42-client.txt](https://github.com/DarkKronicle/KronHUD/files/10474377/crash-2023-01-22_19.59.42-client.txt)

**Comment by allinkdev** [comment]
You are using a version of KronHUD for 1.19.2. Please download the correct version, for 1.19.3, [here](https://github.com/DarkKronicle/KronHUD/releases/tag/v2.2.4).

**Comment by Shiroiame-Kusu** [comment]
My bad , sorry.
I download KronHUD from official curseforge page, so I thought 2.2.3 was the latest version.
All the functions seem to work normally after updating to 2.2.4.
Thanks for your reply.
