### ISSUE TITLE
Support more Minecraft versions!

### ISSUE THREAD

**Issue by JavaCoffeePro** [DarkKronicle/KronHUD#13]
I am Chinese, I used Google Translate to translate this suggestion! It may be a bit incorrect, but please read it through!

This is a great mod, but we need to make it support more versions! For example 1.7.10 / 1.8.9 / 1.12.2! I used this mod in 1.16.2, and I think it is very suitable for playing Hypixel! But I did not find a mod version that supports 1.8.9! Because 1.8.9 has not been "Combat Updat", and for the latest version, 1.8.9 will be more stable and mature! So I hope it can support 1.8.9 or more.

I hope the author will adopt this suggestion!

**Comment by DarkKronicle** [comment]
Thanks for the request! Currently creating mods for different versions is a really complex process. I am also using a couple other mods wrapped into KronHUD to make my life easier. If it was easy to create 1.8 versions and above I would totally do it! But for now there are no plans on releasing a version lower than 1.16. There are lots of other PvP HUD mods for 1.8 that you can find.

**Comment by JavaCoffeePro** [comment]
Okay, but your mod is really good! I will always follow your updates! Looking forward to the day when you release support version 1.8.9!
