### ISSUE TITLE
Update to 1.20 & 1.20.1

### ISSUE THREAD

**Issue by gitdrug** [DarkKronicle/KronHUD#144]
Update to 1.20 & 1.20.1

**Comment by TwinShards** [comment]
Don't ask. He's clearly working on it but as long DarkKore is not 1.20+ He cannot make final progress.

If you get something for free, don't ask for it. Just close this post.

**Comment by gitdrug** [comment]
> Don't ask. He's clearly working on it but as long DarkKore is not 1.20+ He cannot make final progress.
> 
> If you get something for free, don't ask for it. Just close this post.

It was just a issue so when it does get updated in the future people can see buy seeing this issue as closed wasnt trying to be arrogant

**Comment by TheKodeToad** [comment]
It helps track it, so i don't think it's much of an issue
