### ISSUE TITLE
Modules can still be clicked or moved when they are disabled.

### ISSUE THREAD

**Issue by cs127** [DarkKronicle/KronHUD#15]
**Describe the bug**
Modules can still be clicked or moved around when they are disabled, and I'm pretty sure this isn't intentional.

**Expected behavior**
Disabled modules should not be able to be clicked or moved.

**Comment by Excigma** [comment]
For me, at least, they're hidden and unable to be moved when disabled.

**Comment by DarkKronicle** [comment]
Sorry that I took so long to respond... I've been pretty burnt out with modding. What version are you using? I remember this being a problem on older versions.

**Comment by cs127** [comment]
Sorry for not specifing the version! I don't exactly remember what version I was using when I opened this issue, but I still have the same problem with the latest version.
I'm currently using version 1.1.1 with Minecraft 1.16.4, Fabric loader 0.10.7, and Fabric API 0.25.7.
I am using other mods too, but I also tried it without any other mods and still had the same problem.
