### ISSUE TITLE
Crash when using mod menu to configure

### ISSUE THREAD

**Issue by NoComment1105** [DarkKronicle/KronHUD#17]
**Describe the bug**
When using mod menu to configure the HUD, the moment you click configure button the game crashes

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the game with mod menu installed
2. Open mod menu on the title screen
3. Click the configure button
4. CRASH

**Expected behaviour**
KronHUD config opens

[crash-2020-10-29_17.14.16-client.txt](https://github.com/DarkKronicle/KronHUD/files/5460174/crash-2020-10-29_17.14.16-client.txt)

**Comment by DarkKronicle** [comment]
Oh ok. I think I figured out why it crashes. For now don't use the modmenu config in the title screen. It shouldn't crash if you're in a world.

**Comment by NoComment1105** [comment]
Okay thank you, it does work perfectly when in a world :)
