### ISSUE TITLE
FPS halving while Using KronHUD

### ISSUE THREAD

**Issue by Paradox-77** [DarkKronicle/KronHUD#19]
Whenever I try to use this mod my FPS almost halves. This mod is great and I would love to use it without lag spikes

1. Launch Minecraft Fabric with Kron HUD mod and Fabric API
2. Go into single-player or multi-player
3. You will see that either your fps is low or halved

I expected this mod to only reduce my fps by a little Eg: 300 to 275

**Comment by DarkKronicle** [comment]
Does the FPS half when you have no modules active? If you wouldn't mind, if you could let me know which one is the most laggy I could focus my attention on that.

**Comment by Paradox-77** [comment]
Yes sure in a week or so, im really busy rn. Sorry.

**Comment by Samisaprogrammer** [comment]
Hey, I'm having this issue too. Using kronHUD 1.1.0, keystrokeshud, cpshud, pinghud, armorhud, arrowhud, fpshud and potionhud.

**Comment by jeffrgh** [comment]
Latest ver here https://drive.google.com/file/d/1Zer5xPsVRyydB8vD83VSKqeZVY18bfPF/view?usp=sharing

**Comment by Samisaprogrammer** [comment]
Stop posting this

**Comment by DarkKronicle** [comment]
Seems to have improved significantly
