### ISSUE TITLE
[Suggestion] Horizantal Potion/Status bar

### ISSUE THREAD

**Issue by MechanosG** [DarkKronicle/KronHUD#20]
**Describe what you would like**
An option to make the potion/status bar render horizontally instead of vertically.

**Additional context**
I personally like the default vertical widget, but I'm currently using VoxelMap, and VoxelMap moves downward when you have a status effect applied, expecting the vanilla status icons to be there.  So I would like to place KronHUD's status bar where Vanilla would normally render it, and have the icons list right to left, that way it plays nice with VoxelMap.

(Also, thx for this mod, I love how configurable it is.)

Edit: Ok, I was wrong.  Vanilla buffs stack up an down too, and VoxelMap continues to move downward the more buffs you get.  I'm dumb lol.  Horizontal buff bar in KronHUD would still be cool though, so I'll leave this suggestion here.

**Comment by DarkKronicle** [comment]
Implemented
