### ISSUE TITLE
Mod Uses Unreleased Version of Polish

### ISSUE THREAD

**Issue by TheKodeToad** [DarkKronicle/KronHUD#24]
**Describe the bug**
I wanted to contribute to this mod, but the public version of Polish on GitHub cannot be used to compile this mod, as it is missing various methods and classes. I tried to use the version of Polish bundled with the pre-built mod, but it uses the intermediary mappings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone https://github.com/DarkKronicle/Polish.git and run `./gradlew build`.
2. Clone https://github.com/DarkKronicle/KronHUD.git.
3. Copy "Polish/build/libs" to "KronHud/libs".
4. Run `./gradlew build` in KronHUD.

**Expected behaviour**
I expected the mod to compile with the public .

**Suggested Solutions**
3 solutions I thought of:
- Remove "libs" from ".gitignore" and add the libs folder in a commit.
- Commit the unpublished changes to the public Polish repository.
- Change the code to work with the public Polish version.

**Comment by DarkKronicle** [comment]
Just pushed to Polish, let me know if that works. If it doesn't I'll try adding the libs from the repo.

**Comment by TheKodeToad** [comment]
Looking at the other issues, I expected it to take months to be fixed. Thank you for fixing it so quickly!

**Comment by DarkKronicle** [comment]
I haven't been super motivated to work on KronHUD, so I haven't done too much development on it. But quick changes such as Polish are easy :) If you want, you can ask me any questions on KronHUD on discord, or just tell me what you're planning on adding (I'm curious). Glad I could help! https://discord.gg/WnaE3uZxDA

**Comment by TheKodeToad** [comment]
I was planning on fixing a few bugs and adding more customisation such as the ability to enable and disable backgrounds and text shadows, and align potion effects properly/

**Comment by TheKodeToad** [comment]
Shall I also open a pull request to switch from Polish to ClothConfig, like you did with AdvancedChat? Polish looks nice, but is less complete that ClothConfig.
