### ISSUE TITLE
1.17 Update

### ISSUE THREAD

**Issue by Diclo** [DarkKronicle/KronHUD#27]
**Describe what you would like**
greetings
update for mc 1.17

**Additional context**
https://i.imgur.com/bkxuRxr.png

**Comment by Samisaprogrammer** [comment]
+1

**Comment by Rajbir98** [comment]
plz update too 1.17.1 without kron hud i cant play like pro players :(

**Comment by Rajbir98** [comment]
plz update too 1.17.1 without kron hud i cant play like pro players :(

**Comment by Boobies** [comment]
It already works for 1.17.1...
