### ISSUE TITLE
Error message when I launch MC

### ISSUE THREAD

**Issue by Thareya** [DarkKronicle/KronHUD#3]
When I try to launch the game with the latest version of Fabric I have an error message "Could not find required mod: kronhud requires {fabric @ [*]}".

**Comment by Excigma** [comment]
Do you have the Fabric API installed?

**Comment by DarkKronicle** [comment]
As @Excigma said, is the Fabric API installed? (Thanks also Excigma for helping)

**Comment by DarkKronicle** [comment]
Closed due to no response
