### ISSUE TITLE
Are you gonna update to 1.17?

### ISSUE THREAD

**Issue by JackTGG** [DarkKronicle/KronHUD#31]
**Describe what you would like**
Are you gonna update this mod to 1.17.1?
**Additional context**
Add any other context or screenshots about the feature request here. (Is there something similar to this, is this already partially added...)

**Comment by SUPERN00Bthefirst** [comment]
Duplicate of #27

**Comment by JackTGG** [comment]
Not really 1.17 is different from 1.17.1 I sent this when 1.17 was out.

**Comment by TheKodeToad** [comment]
This probably won't happen unless somebody (sigh, probably me) creates another pull request (see https://github.com/DarkKronicle/KronHUD/issues/24#issuecomment-808344152).

**Comment by JackTGG** [comment]
Nice malilib is a good lib
