### ISSUE TITLE
Custom Crosshair Resizing (And maybe custom crosshair texture)

### ISSUE THREAD

**Issue by NathZen** [DarkKronicle/KronHUD#33]
KronHUD is very useful for me, I can move the HUD anywhere on my monitor.
But it will good if it has "Custom Crosshair" for it. And yes, can modify the texture of the Crosshair (or at least, don't replace the other's resource pack into KronHUD's default crosshair)

In my condition, GUI Scale: 2 work best for my monitor and my eyes. But the crosshair is small if I use GUI Scale 2.
If I use GUI Scale: 3, The crosshair is good enough to see (Doesn't blending with the objects) but the HUD and everything are too big.

Looking forward for future updates

**Comment by TheKodeToad** [comment]
Can't you change the scale of the crosshair?

**Comment by TheKodeToad** [comment]
Try changing option called "Scale" for the crosshair.

**Comment by DarkKronicle** [comment]
Custom texture will be added next update
