### ISSUE TITLE
KronHUD 2.0.0 Removed "DisableVanillaPotionHUD" Option?

### ISSUE THREAD

**Issue by IJustWantANamePlease** [DarkKronicle/KronHUD#36]
**Describe the bug**
idk if this should be a bug report or feature request tbh. Anyway, in KronHUD 2.0.0 the "DisableVanillaPotionHUD" option seems to be removed. I really love the vanilla HUD and actually want to have both present, so please add this back.

**To Reproduce**
1. Go to kronhud.json
2. "DisableVanillaPotionHUD" option is gone

**Comment by TheKodeToad** [comment]
That was my fault (#35). I wasn't sure where the option should be.

**Comment by IJustWantANamePlease** [comment]
> 
> 
> That was my fault (#35). I wasn't sure where the option should be.

Maybe put it in configuration menu of PotionHUD? To me it  suits well there.
