### ISSUE TITLE
Crash after joining the world

### ISSUE THREAD

**Issue by Ro-off** [DarkKronicle/KronHUD#4]
Initially everything worked, but after one of the restarts (in order to install several other mods), this mod start crashing mincraft.
Downloading the mods again did not help.
Disabling other mods also (disabled all other mods on video).

[Crash](https://youtu.be/VYdDGQjlSBc)

[Error](https://i.yapx.ru/IwrgP.png)

**Comment by Ro-off** [comment]
Removing the /config/kronhud folder helped to solve the problem.

**Comment by Ro-off** [comment]
I've restored the folder with the config leading to an error, here it is:
[kronhud.zip](https://github.com/DarkKronicle/KronHUD/files/5143828/kronhud.zip)

**Comment by Ro-off** [comment]
I think I found what the problem is.
I tried to diagnose the problem by partially modifying the working config with parameters from the baggy config.

And the problem appeared when the line responsible for "keystrokeHudStorage" was replaced with "enabled": false.

**Comment by DarkKronicle** [comment]
Found the problem. If it was disabled some things didn't get set and tried to iterate through those non set things. Should be fixed next update (which will come out soon!). Thanks for the report!
