### ISSUE TITLE
modrinth is not up to date

### ISSUE THREAD

**Issue by Samisafool** [DarkKronicle/KronHUD#43]
**Describe the bug**
Modrinth still has only 1.16

**To Reproduce**
1. Go to https://modrinth.com/mod/kronhud
2. Use your eye(s)

**Expected behavior**
It should have 1.17 and also 1.18 when it's out

**Screenshots**
![image](https://user-images.githubusercontent.com/59611020/145153253-de4a5c46-540a-458c-90a9-2f71b517aa7b.png)

**Additional context**

**Comment by bilibilixiaotong** [comment]
Can you make the fabric version of 1.16.5?
