### ISSUE TITLE
Mod Incompatible with 1.18.1 on Fabric

### ISSUE THREAD

**Issue by Tj7223** [DarkKronicle/KronHUD#44]
Mod fails to load on 1.18.1, due to dependencies specifically listing 1.18.

From what I can tell the fix should be as simple as updating the dependencies in `gradle.properties`, `build.gradle`, and `fabric.mod.json`.

I was able to do this myself, and recompiled & loaded it successfully, but I'm not an experienced github user so I don't trust myself to make a proper PR (plus for all I know my proposed fix screws something up really badly).

Thank you!

**Comment by DarkKronicle** [comment]
Should be fixed now. Thanks!
