### ISSUE TITLE
Separating the Crosshair Attack Indicator Customizability from the Crosshair Customizability Itself

### ISSUE THREAD

**Issue by Tj7223** [DarkKronicle/KronHUD#46]
It would be great to be able to customize the attack indicator without fully overwriting a resource pack's crosshair. This would be particularly useful since resource packs meant for pre-combat update versions of the game seem to fully hide the attack indicator. This could possibly be as simple as adding an "Overwrite Resource Pack Crosshair" toggle to the configuration screen.

**Comment by DarkKronicle** [comment]
Could you just set the attack indicator to transparent?

**Comment by Tj7223** [comment]
I think you may have misunderstood my intent. What I'm saying is that it would be useful to be able to use the mod's customizable attack indicator without using its crosshair. Currently that is not possible, one can either use the resource pack's crosshair and attack indicator or the mod's crosshair and attack indicator.

**Comment by DarkKronicle** [comment]
Oh ok. Like #33?

**Comment by Tj7223** [comment]
Correct, except specifically to be able to customize the attack indicator without overwriting the resource pack. The author of that issue did not specify this as such.

**Comment by DarkKronicle** [comment]
It will be added in 2.0.2
