### ISSUE TITLE
Display the arrow type selected

### ISSUE THREAD

**Issue by sorat0mo** [DarkKronicle/KronHUD#49]
**Describe what you would like**
Currently, the sum of arrows in the inventory is displayed with the arrow hud. I suggest making this more accurate by:
1. Displaying the arrow would be used by the bow, that is, the top left most stack of arrows. Along with their respective icons.
2. Option to display stacks being used instead of the sum of arrows in inventory.
3. Maybe also an infinity sign for using standard arrows with an infinity bow.

**Additional context**
Add any other context or screenshots about the feature request here. (Is there something similar to this, is this already partially added...)

**Comment by DarkKronicle** [comment]
Oh cool! 1 and 2 will be added.
