### ISSUE TITLE
Movement keys on the keystrokes doesn't render

### ISSUE THREAD

**Issue by maxigator** [DarkKronicle/KronHUD#5]
I'm using the mod and the keystrokes only show grey boxes without anything inside of it.

1. Download [Mouse Wheelie mod](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie) and add it to the mods folder
2. Enable the keystrokes
3. See that the letters don't show up

![2020-08-29_11 25 25](https://user-images.githubusercontent.com/22241832/91633644-638c9c80-e9ea-11ea-9373-c526d79dae06.png)

**Comment by maximeurban** [comment]
Error with mousewheelie

**Comment by DarkKronicle** [comment]
What keys are you using for movement? 

And do the Keystrokes change color when you press them? Or does nothing happen?

Thanks for the report!

**Comment by maximeurban** [comment]
I am using ZQSD controls and the box changes color when I press the corresponding key.
Only the letter isn't rendering

**Comment by jeffrgh** [comment]
This version has your fix https://drive.google.com/file/d/1Zer5xPsVRyydB8vD83VSKqeZVY18bfPF/view?usp=sharing
