### ISSUE TITLE
1.17.1 Backport?

### ISSUE THREAD

**Issue by CreeperCoder63** [DarkKronicle/KronHUD#57]
**Describe what you would like**
Is there a way to Backport to 1.17.1? I’m making a modpack of that version for personal use.
**Additional context**
A lot of modders still make 1.17.1 modpacks so I don’t think it’s a benefit only for me.

**Comment by TheKodeToad** [comment]
There is a 1.17 version (https://www.curseforge.com/minecraft/mc-mods/kronhud/files/3441441).

**Comment by CreeperCoder63** [comment]
> It doesn't have all the new features.
Yes, that’s why a Backport would be useful.

**Comment by moehreag** [comment]
A backport of a newer version is unfeasable since the work is simply too much in relation to the resulting profit,
e.g. it would require someone backporting DarkKore first.

**Comment by CreeperCoder63** [comment]
> A backport of a newer version is unfeasable since the work is simply too much in relation to the resulting profit,
> e.g. it would require someone backporting DarkKore first.

Yeah, I see that now. This version is redundant anyway because I use modded 1.19.2 now
