### ISSUE TITLE
Keystrokes display not showing WASD due to mod incompatibility

### ISSUE THREAD

**Issue by TheWaffleLord** [DarkKronicle/KronHUD#58]
**Describe the bug**
When using KronHUD alongside the [Just Enough Keys](https://www.curseforge.com/minecraft/mc-mods/just-enough-keys-fabric) mod, the WASD keys disappear.

**To Reproduce**
1. Open a world/server with the most recent version of both mods for 1.18.2 installed,
2. See bug.

**Expected behavior**
The WASD keys to be visible.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/94252487/158112646-346d4b28-e518-4d1f-8900-c3b8cbfd8956.png)

**Comment by CreeperCoder63** [comment]
I have had the same issue in the past as I added more mods to a modpack, however I never knew what the mod was conflicting with. Thanks for letting us know it’s those two mods.
