### ISSUE TITLE
Crash when stepping on the pressure plate on server

### ISSUE THREAD

**Issue by NanKillBro** [DarkKronicle/KronHUD#62]
**Describe the bug**
Crash when stepping on the pressure plate

**To Reproduce**
Step on the pressure plate parkour in pika network server lol

**Expected behavior**
Not crash

**Screenshots**
Video: https://www.youtube.com/watch?v=7P2SzPhEVXo

**Additional context**
KronHUD Version: 2.0.3
Minecraft Version: 1.18.2
Java Version: 17.0.1
Fabric Loader: 0.14.5
Crash log: https://pastebin.com/bh5PL1dV
Not crash in Singleplayer

Mod I use with KronHUD: 
advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
alternate-current: Alternate Current 1.2.1
bedrodium: Bedrodium 0.2
betterbeds: Better Beds 1.2.0
betterfpsdist: Better FPS distance Mod 1.18-1.7
betterpingdisplay: Better Ping Display 1.1.1
borderlessmining: Borderless Mining 1.1.1+1.18
c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.0
caffeineconfig: CaffeineConfig 1.1.0
cloth-basic-math: cloth-basic-math 0.6.0
cloth-config: Cloth Config v6 6.2.57
clumps: Clumps 8.0.0+7
collective-fabric: Collective (Fabric) 4.26
confabricate: confabricate 3.0.0-SNAPSHOT+4.1.2
craftpresence: CraftPresence 1.8.8
crowdin-translate: CrowdinTranslate 1.4+1.18.2
cull-less-leaves: Cull Less Leaves 1.0.0
cullleaves: Cull Leaves 2.3.2
dashloader: DashLoader 3.1.1+1.18
debugify: Debugify 1.10.0
dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
dev_quantumfusion_hyphen: hyphen 0.2.0
dimthread: DimensionalThreading 1.2.6
durabilityviewer: Giselbaers Durability Viewer 1.18.2-fabric0.47.10-1.10.3
dynamicfps: Dynamic FPS 2.1.0
enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
entityculling: EntityCulling-Fabric 1.5.0
fabric: Fabric API 0.48.0+1.18.2
farsight: Farsight Mod 1.18-1.9
fastchest: FastChest 1.2+1.18
ferritecore: FerriteCore 4.2.0
fiber: fiber 0.23.0-2
forcecloseloadingscreen: kennytv's epic force close loading screen mod for Fabric 1.1.0
fullbrightnesstoggle-fabric: Full Brightness Toggle (Fabric) 1.3
gammautils: Gamma Utils 1.5.6
gbfabrictools: GBfabrictools 1.3.4+1.18.2
indium: Indium 1.0.2+mc1.18.2
iris: Iris 1.2.2-build.32
justload: Justload 1.0.0+mc1.18.2
kronhud: KronHUD 2.0.3
krypton: Krypton 0.1.9
lambdynlights: LambDynamicLights 2.1.0+1.17
lazy-language-loader: lazy-language-loader 0.3.0
lazydfu: LazyDFU 0.1.2
lithium: Lithium 0.7.9
logical_zoom: Logical Zoom 0.0.14
malilib: MaLiLib 0.12.1
midnightlib: MidnightLib 0.2.9
minecraft: Minecraft 1.18.2
modmenu: Mod Menu 3.1.0
oauth-fabric: Oauth ${version}
placeholder-api: Placeholder API 1.1.3+1.17.1
pride: Pride Lib 1.1.0+1.17
purpurclient: Purpur Client 1.18.2-3
reeses-sodium-options: Reese's Sodium Options 1.4.2
replaymod: Replay Mod 1.18.2-2.6.4
servercore: ServerCore 1.2.9-1.18.2
skiptransitions: Skip Transitions 1.3.2+1.18.x
smoke_suppression: Smoke Suppression 1.0.9-1
smoothboot: Smooth Boot 1.18.2-1.7.0
sodium: Sodium 0.4.1+build.15
sodium-extra: Sodium Extra 0.4.3
spruceui: SpruceUI 3.3.0+1.17
starlight: Starlight 1.0.2+fabric.89b8d9f
wthit: wthit 4.8.0

**Comment by moehreag** [comment]
This will probably already be fixed in the next version of KronHUD. Could you try it maybe with a build of the latest commit?

**Comment by DarkKronicle** [comment]
I should hopefully get around to updating by tonight
