### ISSUE TITLE
Incompatibility with Debugify

### ISSUE THREAD

**Issue by isXander** [DarkKronicle/KronHUD#64]
**Describe the bug**
[KronHud's mixin](https://github.com/DarkKronicle/KronHUD/blob/master/src/main/java/io/github/darkkronicle/kronhud/mixins/MixinInGameHud.java#L52-L61) conflicts with [Debugify's mixin](https://github.com/isXander/Debugify/blob/ee90a2eab26b1c9d2481a7282320773fd697f884/common/src/main/java/dev/isxander/debugify/mixins/basic/client/mc145929/InGameHudMixin.java)

This would also create compatibilities with similar mods such as [TieFix](https://github.com/j-tai/TieFix/blob/master/src/main/java/ca/jtai/tiefix/mixin/mc145929/InGameHudMixin.java) and [shadowedactionbar](https://github.com/KabanFriends/ShadowedActionBar/blob/master/src/main/java/io/github/kabanfriends/shadowedactionbar/mixin/MixinGui.java)

I propose you use [MixinExtra's WrapWithCondition](https://github.com/LlamaLad7/MixinExtras/wiki/WrapWithCondition) where you can check if the action bar hud is enabled, render it and return false, to prevent the code from running (with a higher priority).
I know this isn't ideal but there isn't really another way to add a shadow to the text.

**Comment by TheKodeToad** [comment]
An extra dependency doesn't feel great.

**Comment by isXander** [comment]
It's very small!

**Comment by TheKodeToad** [comment]
If it's small and fixes compatibility, it's probably worth it then.
I would open a pull request, but I think I'll wait for a 1.19 update.

**Comment by DarkKronicle** [comment]
Seems to be fixed
