### ISSUE TITLE
Crash when initializing the game

### ISSUE THREAD

**Issue by RoonMoonlight** [DarkKronicle/KronHUD#70]
**Describe the bug**
Crash when initializing the game. Most likely a getActionBar bug.

**To Reproduce**
[Game Log](https://gist.github.com/RoonMoonlight/983852a598e3097e4539fdd82abd2eef)

**Expected behavior**
The game should launch normally without issue, I even have MaLiLib installed.

**Screenshots**
Log posted instead of screenshot because it is just a crash

**Additional context**
None.

**Comment by moehreag** [comment]
This is just caused by 1.19.1 not using TextRenderer.draw, but TextRenderer.drawWithShadow. (That's why the injection fails.)
I'll open a PR soon to fix this.
