### ISSUE TITLE
Control and Sound Settings get set to default value when launching 

### ISSUE THREAD

**Issue by mmmmmabil** [DarkKronicle/KronHUD#76]
**Describe the bug**
when launching the game both controls and the sound settings are on their default value

**To Reproduce**
1. download kronhud v2.1.2 and dependencies
2. launch the game and change hotkeys and sound settings
3. close the game
4. lauch the game again and visit the settings screen to see that the changes have been reset

**Expected behavior**
settings persist upon restart

**Additional context**
logs of the time the settings were chaged:
 - https://mclo.gs/wiJh6aB
logs of the second time the game was launched 
 - https://mclo.gs/abYotCa

**Comment by mmmmmabil** [comment]
error in the logs 
![image](https://user-images.githubusercontent.com/95183826/189361116-58c477ce-c226-4451-9913-d8b2722e6aaa.png)

**Comment by mmmmmabil** [comment]
for the example i changed:
-strafe left to 1
-strafe right to 2
-walk backwards to 3
-walk forwards to 4

odly enought walk forward persisted while the other 3 got set to the default

**Comment by cleverActon0126** [comment]
Skin customization also gets set to default.

**Comment by DarkKronicle** [comment]
Should be fixed now
