### ISSUE TITLE
Options.txt fails to load when mod is active

### ISSUE THREAD

**Issue by HiHi3690** [DarkKronicle/KronHUD#80]
Desc:
When using this mod, no changes to several sections of the options menu (Music, Video, Controls) fail to save/load from options.txt. This occurs on MultiMC launchers, and I haven't been able to check any others.

How to Reproduce:
-Install this mod's latest version 
-Change anything in the music, video, or control settings
-Reboot your game
-View any changed settings

**Comment by DarkKronicle** [comment]
This should be fixed in the newest version, if it's not you can check out the beta [here](https://github.com/DarkKronicle/KronHUD/actions/runs/3148499979) Download the artifact and get the jar from that
