### ISSUE TITLE
the keystrokes is invisible

### ISSUE THREAD

**Issue by Lucas104-alt** [DarkKronicle/KronHUD#83]
**Describe the bug**
it's like it doesn't appear and the size is reduced

**To Reproduce**
i don not

**Expected behavior**
the keystrokes is invisible
**Screenshots**
![image](https://user-images.githubusercontent.com/63660708/194761738-e2efef12-794b-4942-9e61-7272b91645f9.png)

**Additional context**

**Comment by DarkKronicle** [comment]
Working on a massive update that should hpoefully fix this. Should be released soon.
