### ISSUE TITLE
Scoreboard background is too big

### ISSUE THREAD

**Issue by gepron1x** [DarkKronicle/KronHUD#85]
**Describe the bug**
Now the scoreboard is just big, independently of the scoreboard size itself.
![изображение](https://user-images.githubusercontent.com/56407064/195698791-dca27d50-8052-4c58-9f24-6d20812d574e.png)
I made the background red to make difference more obvious. this happens on latest

**To Reproduce**
1. Enable scoreboard module

**Comment by DarkKronicle** [comment]
This is fixed in the betas, you can download it by going to actions -> betas -> latest and then download the archive. when I publish the next release this will be fixed.
