### ISSUE TITLE
[BUG] Crosshair Resourcepack option not working correctly

### ISSUE THREAD

**Issue by MarkinhosMLP** [DarkKronicle/KronHUD#87]
Im playing with my own resourcepack, but it isnt applying the correct textures from icon.png, im also playing in origin realms server which has a resourcepack that uses vanillashaders feature, but without the mod the crosshair textures stays the same
the weird is that this started happenning when changed to DarkKore so maybe its a darkkore bug affecting it? idk

**Comment by DarkKronicle** [comment]
Hmm. Can you send a screenshot of what it looks like?

**Comment by MarkinhosMLP** [comment]
in game looks like this

![image](https://user-images.githubusercontent.com/47507632/195758400-adfbe2ec-af47-49ec-aac0-ca8af4060595.png)

in the resource pack it is like this

![image](https://user-images.githubusercontent.com/47507632/195758466-b1a1fe07-c14e-4315-ac26-25016d3207e0.png)

**Comment by MarkinhosMLP** [comment]
Also noticed that resizing the Dot crosshair is weird, like its offset
Scale/Size 2.0 looks like this
![image](https://user-images.githubusercontent.com/47507632/195758834-cedec6ae-5654-419f-9016-e71300bfd7e3.png)

**Comment by DarkKronicle** [comment]
Oh looks like I messed up a few numbers when refactoring. I will have this done by tomorrow.

**Comment by MarkinhosMLP** [comment]
also, i got this crash while opening a shulker box, idk if it is related to the fact that the crosshair changes the color when looking at containers, but it is weird 

![image](https://user-images.githubusercontent.com/47507632/195759701-d1d38fe3-450e-494a-9853-848b8bfac541.png)

**Comment by DarkKronicle** [comment]
Will be fixed next update (probably will push soon)

**Comment by MarkinhosMLP** [comment]
it is fixed but the default color option, if set with transparency/translucency, it wont work, but instead will be fully opaque
