### ISSUE TITLE
Cannot exit the config of a specific module

### ISSUE THREAD

**Issue by Madis0** [DarkKronicle/KronHUD#9]
**Describe the bug**
I haven't figured out how to exit out of a module config screen without exiting the whole KronHUD config.

**To Reproduce**
1. Go to Mod Menu
2. Scroll to KronHUD and click on config button
3. Right click a module
4. Do something, like toggle it off
5. Press Esc to save/return
6. KronHUD config exits entirely 

**Expected behavior**
I expected to go back to previous screen, so I could edit the config of another module.

**Screenshots**
N/A

**Additional context**
KronHUD 1.1.1
MC 1.16.3
Fabric API 0.20.2 b 402

**Comment by DarkKronicle** [comment]
This will be one of the next things I fix. Thanks for the report!

**Comment by Samisaprogrammer** [comment]
It's been a few months, when does this get fixed? I'm sorry I know this is opensource and I know you're not getting paid for this but still.

**Comment by jeffrgh** [comment]
I think the new version here has your fix https://drive.google.com/file/d/1Zer5xPsVRyydB8vD83VSKqeZVY18bfPF/view?usp=sharing

**Comment by Samisaprogrammer** [comment]
Yeah, i'd rather not trust a google drive link.

**Comment by jeffrgh** [comment]
> I think the new version here has your fix https://drive.google.com/file/d/1Zer5xPsVRyydB8vD83VSKqeZVY18bfPF/view?usp=sharing

no no it doesn't have your fix I tried it

**Comment by jeffrgh** [comment]
> Yeah, i'd rather not trust a google drive link.

Honestly what do you trust

**Comment by Samisaprogrammer** [comment]
idk github releases or modrinth or curseforge, but i looked on the discord server and apparently its not a virus

**Comment by jeffrgh** [comment]
Thanks for believing in me

**Comment by jeffrgh** [comment]
> idk github releases or modrinth or curseforge, but i looked on the discord server and apparently its not a virus

The reason I posted here is because there not this ver on curseforge or modrinth or as a github release

**Comment by Samisaprogrammer** [comment]
you could just... idk..... link to the original author posting the link

**Comment by jeffrgh** [comment]
ok here's proof 
![image](https://user-images.githubusercontent.com/84900057/124216451-f66afb80-db13-11eb-9fd4-ad4b7b8f31f4.png)

**Comment by Samisaprogrammer** [comment]
i already know now stop this convo somebody is probably really pissed at us right now

**Comment by jeffrgh** [comment]
lol nobody has checkd here in ages

**Comment by Samisaprogrammer** [comment]
STFU they get an email everytime theres a msg
i wont reply anymore
