### ISSUE TITLE
Some of modules reset their position

### ISSUE THREAD

**Issue by gepron1x** [DarkKronicle/KronHUD#91]
**Describe the bug**
Some modules have positions different from what i set after game restart.

**To Reproduce**
1. Put some modules near the screen corners;
2. Restart the game

**Screenshots**
Before restart
![изображение](https://user-images.githubusercontent.com/56407064/195886793-3c629aef-e94f-4ac9-b6ce-a085442786bb.png)
After restart
![изображение](https://user-images.githubusercontent.com/56407064/195887038-db4bb69d-37a4-4b83-8cbb-02e764d6ff25.png)

**Additional context**
I use beta jar from Actions.

**Comment by gepron1x** [comment]
Just checked the latest release, same thing happens

**Comment by DarkKronicle** [comment]
Hmm. Does the same thing happen when you resize the screen to small and large again?

**Comment by gepron1x** [comment]
> Hmm. Does the same thing happen when you resize the screen to small and large again?

Yeah. Exactly

**Comment by DarkKronicle** [comment]
Ok, I know the problem

**Comment by DarkKronicle** [comment]
Will be fixed next update
